'use client';
import {useEffect,useRef,useState} from 'react';

type Telemetry={type:string;timestamp:string;people:any[];signal:any;vitals:any;system:any};
const API=process.env.NEXT_PUBLIC_API_BASE||'http://localhost:8000';
function Spark({points}:{points:number[]}){const d=points.map((v,i)=>`${(i/Math.max(1,points.length-1))*100},${48-v*24}`).join(' ');return <svg viewBox="0 0 100 60" preserveAspectRatio="none" className="h-16 w-full"><polyline points={d} fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}
function Radar({people}:{people:any[]}){return <div className="relative h-[420px] overflow-hidden rounded-xl glass scan flex items-center justify-center"><div className="absolute h-72 w-72 rounded-full border border-cyan-400/30 shadow-[0_0_45px_rgba(72,231,255,.12)]"/><div className="absolute h-52 w-52 rounded-full border border-cyan-400/20"/><div className="absolute h-32 w-32 rounded-full border border-cyan-400/15"/><div className="absolute h-px w-full bg-cyan-400/10"/><div className="absolute w-px h-full bg-cyan-400/10"/>{people.map((p,i)=><div key={p.id||i} className="absolute" style={{left:`${p.x*100}%`,top:`${p.y*100}%`}}><div className="h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-cyan-300 bg-cyan-300/20 shadow-[0_0_25px_#48e7ff]"/><div className="absolute left-3 -top-2 text-[10px] text-cyan-200">{p.id}</div><div className="absolute -left-5 top-4 text-[9px] text-lime-300">{p.activity}</div></div>)}</div>}
export default function Home(){const [t,setT]=useState<Telemetry|null>(null);const [mode,setMode]=useState('simulator');const [consent,setConsent]=useState(false);const [recording,setRecording]=useState(false);const [cal,setCal]=useState(false);const [raw,setRaw]=useState<number[]>([]);const [view,setView]=useState('Live sensing');const csrf=useRef('local-dev-csrf');
useEffect(()=>{fetch(`${API}/api/config`).then(r=>r.json()).then(x=>{csrf.current=x.csrfToken;setMode(x.mode);setCal(x.calibrated)}).catch(()=>{});const ws=new WebSocket(API.replace(/^http/,'ws')+'/ws/telemetry');ws.onmessage=e=>{const x=JSON.parse(e.data);setT(x);setRaw(r=>[...r.slice(-90),Number(x.signal?.variance||0)*120])};return()=>ws.close()},[]);
async function mutate(path:string,body?:any){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf.current},body:body?JSON.stringify(body):undefined});return r.json()}
const metric=(t?.vitals?.breathingRate?.value??null);return <main className="min-h-screen p-4 md:p-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><div className="text-xl font-bold tracking-[.25em] text-cyan-200">AETHERSENSE</div><div className="text-[10px] text-slate-400">LOCAL EDGE SENSOR · CSI RESEARCH CONSOLE</div></div><div className="flex items-center gap-2 text-xs"><span className="rounded-full border border-lime-400/30 px-2 py-1 text-lime-300">LOCAL ONLY</span><select value={mode} onChange={async e=>{setMode(e.target.value);await mutate('/api/mode',{mode:e.target.value})}} className="glass rounded px-2 py-1"><option>simulator</option><option>esp32</option><option>replay</option></select></div></header>
<div className="mb-4 rounded-lg border border-cyan-400/15 bg-cyan-400/5 p-3 text-[11px] text-cyan-100">Wi-Fi sensing detects signal disturbances. It does not capture images or audio. Vital-sign and pose outputs are experimental estimates.</div>
<div className="grid gap-4 xl:grid-cols-[1.7fr_.9fr]"><section><Radar people={t?.people||[]}/><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Presence',t?.people?.length?'DETECTED':'CLEAR'],['People',String(t?.people?.length||0)],['Motion',t?.people?.[0]?.activity||'stationary'],['Packets',String(t?.signal?.packetRate||0)+'/s']].map(([a,b])=><div className="glass rounded-lg p-4" key={a}><div className="text-[10px] text-slate-500">{a}</div><div className="mt-1 text-lg text-cyan-200">{b}</div></div>)}</div></section>
<aside className="space-y-4"><div className="glass rounded-xl p-4"><div className="mb-3 text-xs tracking-widest text-violet-300">SUBJECT TELEMETRY</div><div className="grid grid-cols-2 gap-3 text-xs"><div><div className="text-slate-500">Activity</div><div>{t?.people?.[0]?.activity||'—'}</div></div><div><div className="text-slate-500">Confidence</div><div>{Math.round((t?.people?.[0]?.confidence||0)*100)}%</div></div><div><div className="text-slate-500">Breathing</div><div>{metric==null?'—':`${metric} bpm`}</div></div><div><div className="text-slate-500">Heart rate</div><div>{t?.vitals?.heartRate?.value==null?'—':`${t.vitals.heartRate.value} bpm`}</div></div><div><div className="text-slate-500">Signal</div><div>{t?.signal?.quality||'—'}</div></div><div><div className="text-slate-500">Calibration</div><div className={cal?'text-lime-300':'text-amber-300'}>{cal?'READY':'REQUIRED'}</div></div></div></div>
<div className="glass rounded-xl p-4"><div className="mb-2 text-xs tracking-widest text-cyan-300">MICRO-MOTION WAVEFORM</div><div className="text-cyan-300"><Spark points={raw}/></div><div className="mt-2 text-[10px] text-slate-500">Filtered CSI variance · experimental signal only</div></div>
<div className="glass rounded-xl p-4"><label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-0.5"/><span>I consent to local CSI session recording for this research session.</span></label><div className="mt-3 flex flex-wrap gap-2"><button onClick={async()=>{await mutate('/api/calibrate');setCal(true)}} className="rounded border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200">CALIBRATE</button><button disabled={!consent||recording} onClick={async()=>{await mutate('/api/session/start',{consent:true});setRecording(true)}} className="rounded border border-lime-400/30 px-3 py-2 text-xs text-lime-200 disabled:opacity-40">START</button><button disabled={!recording} onClick={async()=>{await mutate('/api/session/stop');setRecording(false)}} className="rounded border border-rose-400/30 px-3 py-2 text-xs text-rose-200 disabled:opacity-40">STOP</button></div><div className="mt-2 text-[10px] text-slate-500">Recording: {recording?'ACTIVE':'OFF'} · No identity persistence</div></div></aside></div>
<nav className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-7">{['Live sensing','Signal view','Pose estimation','Vital signs','Sessions','Sensor nodes','Settings'].map(x=><button key={x} onClick={()=>setView(x)} className={`rounded border px-2 py-2 text-[10px] ${view===x?'border-cyan-300 bg-cyan-300/10 text-cyan-100':'border-slate-800 text-slate-500'}`}>{x}</button>)}</nav><footer className="mt-4 text-[9px] text-slate-600">AetherSense v0.1 · baseline CSI model · no clinical claims · last telemetry {t?.timestamp||'waiting'}</footer></main>}
